# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  workflow_dispatch:
    inputs:
        version:
          description: "The version to release (eg: 'v1.0.0')"
          required: true
          type: string
        build-artifact:
          description: "Create artifact?"
          required: true
          type: boolean
          default: true
        sign:
          description: "Code sign package?"
          required: true
          type: boolean
          default: true
        draft:
          description: "Create a draft release? (not used)"
          required: false
          type: boolean
          default: true
        prerelease:
          description: "Create a prerelease? (not used)"
          required: false
          type: boolean
          default: true

jobs:
  build:
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
         
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Download and Extract CodeSignTool
      id: codesign
      shell: pwsh
      run: .\download-codesigntool.ps1
        
    - name: Install
      run: npm ci

    - name: Build      
      run: npm run build

    - name: Package
      run: npm run dist
    
    - name: Upload Unpacked
      uses: actions/upload-artifact@v3
      with:
        name: artifact
        path: ./release
        if-no-files-found: error
