# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  workflow_dispatch:
    inputs:
        version:
          description: "The version to release (eg: 'v1.0.0')"
          required: true
          type: string
        build-artifact:
          description: "Create artifact?"
          required: true
          type: boolean
          default: true
        sign:
          description: "Code sign package?"
          required: true
          type: boolean
          default: true
        draft:
          description: "Create a draft release? (not used)"
          required: false
          type: boolean
          default: true
        prerelease:
          description: "Create a prerelease? (not used)"
          required: false
          type: boolean
          default: true

jobs:
  build:
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
         
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'          
    - run: npm ci
    - run: npm run build
    - run: npm run dist

    - name: Download and Extract CodeSignTool
      id: codesign
      run: |
        Set-StrictMode -Version 'Latest'
        
        $downloadUrl = "https://www.ssl.com/download/codesigntool-for-windows/"
        $downloadedFile = "CodeSignTool.zip"
        $extractFolder = "./CodeSignTool"
        $configPath = "/conf/code_sign_tool.properties"
        
        # Download
        Invoke-WebRequest -OutFile $downloadedFile $downloadUrl
                
        # Extract
        Expand-Archive -Path "./$downloadedFile" -DestinationPath $extractFolder -Force
          
        # need to check for a nested single folder as 1.2.7 was packaged without this, all previous versions were not.
        
        $folderCount = @(Get-ChildItem $extractFolder -Directory ).Count;
        
        #if we have a single folder, then assume we have a nested folder that we need to fix
        If ($folderCount -eq 1) {
        
            # get nested folder path, there is only 1 at this point
            $nestedFolderPath = Join-Path $extractFolder (Get-ChildItem $extractFolder -Directory)
        
            # move all child items from this nested folder to it's parent
            Get-ChildItem -Path $nestedFolderPath -Recurse | Move-Item -Destination $extractFolder
        
            # remove nested folder to keep it clean
            Remove-Item -Path $nestedFolderPath -Force
        }
        
        # Set config to sandbox (only while testing)
         
        $codeSignToolPropertiesFile = Join-Path $extractFolder $configPath
        
        New-Item -Path $codeSignToolPropertiesFile -ItemType File -Force
        Add-Content -Path $codeSignToolPropertiesFile -Value "CLIENT_ID=qOUeZCCzSqgA93acB3LYq6lBNjgZdiOxQc-KayC3UMw"
        Add-Content -Path $codeSignToolPropertiesFile -Value "OAUTH2_ENDPOINT=https://oauth-sandbox.ssl.com/oauth2/token"
        Add-Content -Path $codeSignToolPropertiesFile -Value "CSC_API_ENDPOINT=https://cs-try.ssl.com"
        Add-Content -Path $codeSignToolPropertiesFile -Value "TSA_URL=http://ts.ssl.com"
    
    - name: Upload Unpacked
      uses: actions/upload-artifact@v3
      with:
        name: artifact
        path: ./release
        if-no-files-found: error
